#!/bin/bash
#SBATCH -p express
#SBATCH -J second_half_extraction
#SBATCH --time=180:00
source /data/apps/go.sh ### for safety reasons
set -e
cd /data/abattle4/lab_data/GWAS_summary_statistics/PanUKBB/phenotype_flat_files/extract_EUR_scripts
bash continuous-1180-both_sexes.tsv.extract.sh
bash continuous-1190-both_sexes.tsv.extract.sh
bash continuous-1200-both_sexes.tsv.extract.sh
bash continuous-1220-both_sexes.tsv.extract.sh
bash continuous-1239-both_sexes.tsv.extract.sh
bash continuous-1309-both_sexes.tsv.extract.sh
bash continuous-1319-both_sexes.tsv.extract.sh
bash continuous-1329-both_sexes.tsv.extract.sh
bash continuous-137-both_sexes.tsv.extract.sh
bash continuous-1408-both_sexes.tsv.extract.sh
bash continuous-1458-both_sexes.tsv.extract.sh
bash continuous-1478-both_sexes.tsv.extract.sh
bash continuous-1488-both_sexes-irnt.tsv.extract.sh
bash continuous-1498-both_sexes.tsv.extract.sh
bash continuous-1518-both_sexes.tsv.extract.sh
bash continuous-1528-both_sexes.tsv.extract.sh
bash continuous-1588-both_sexes.tsv.extract.sh
bash continuous-1687-both_sexes.tsv.extract.sh
bash continuous-1717-both_sexes.tsv.extract.sh
bash continuous-1737-both_sexes.tsv.extract.sh
bash continuous-1757-both_sexes.tsv.extract.sh
bash continuous-20016-both_sexes-irnt.tsv.extract.sh
bash continuous-20022-both_sexes-irnt.tsv.extract.sh
bash continuous-20127-both_sexes-irnt.tsv.extract.sh
bash continuous-20154-both_sexes-irnt.tsv.extract.sh
bash continuous-20409-both_sexes.tsv.extract.sh
bash continuous-20414-both_sexes.tsv.extract.sh
bash continuous-20453-both_sexes.tsv.extract.sh
bash continuous-20460-both_sexes.tsv.extract.sh
bash continuous-20479-both_sexes.tsv.extract.sh
bash continuous-20512-both_sexes.tsv.extract.sh
bash continuous-2080-both_sexes.tsv.extract.sh
bash continuous-2139-both_sexes-irnt.tsv.extract.sh
bash continuous-2149-both_sexes.tsv.extract.sh
bash continuous-2178-both_sexes.tsv.extract.sh
bash continuous-2217-both_sexes-irnt.tsv.extract.sh
bash continuous-2237-both_sexes.tsv.extract.sh
bash continuous-2267-both_sexes.tsv.extract.sh
bash continuous-23100-both_sexes-irnt.tsv.extract.sh
bash continuous-23101-both_sexes-irnt.tsv.extract.sh
bash continuous-23106-both_sexes-irnt.tsv.extract.sh
bash continuous-2966-both_sexes-irnt.tsv.extract.sh
bash continuous-30000-both_sexes-irnt.tsv.extract.sh
bash continuous-30010-both_sexes-irnt.tsv.extract.sh
bash continuous-30020-both_sexes-irnt.tsv.extract.sh
bash continuous-30040-both_sexes-irnt.tsv.extract.sh
bash continuous-30060-both_sexes-irnt.tsv.extract.sh
bash continuous-30070-both_sexes-irnt.tsv.extract.sh
bash continuous-30080-both_sexes-irnt.tsv.extract.sh
bash continuous-30100-both_sexes-irnt.tsv.extract.sh
bash continuous-30110-both_sexes-irnt.tsv.extract.sh
bash continuous-30120-both_sexes-irnt.tsv.extract.sh
bash continuous-30130-both_sexes-irnt.tsv.extract.sh
bash continuous-30180-both_sexes-irnt.tsv.extract.sh
bash continuous-30190-both_sexes-irnt.tsv.extract.sh
bash continuous-30210-both_sexes-irnt.tsv.extract.sh
bash continuous-30260-both_sexes-irnt.tsv.extract.sh
bash continuous-30300-both_sexes-irnt.tsv.extract.sh
bash continuous-30510-both_sexes-irnt.tsv.extract.sh
bash continuous-30530-both_sexes-irnt.tsv.extract.sh
bash continuous-3062-both_sexes-irnt.tsv.extract.sh
bash continuous-3064-both_sexes-irnt.tsv.extract.sh
bash continuous-3143-both_sexes-irnt.tsv.extract.sh
bash continuous-3148-both_sexes-irnt.tsv.extract.sh
bash continuous-3761-both_sexes-irnt.tsv.extract.sh
bash continuous-400-both_sexes-irnt.tsv.extract.sh
bash continuous-404-both_sexes-irnt.tsv.extract.sh
bash continuous-4080-both_sexes-irnt.tsv.extract.sh
bash continuous-4195-both_sexes-irnt.tsv.extract.sh
bash continuous-4282-both_sexes.tsv.extract.sh
bash continuous-4290-both_sexes-irnt.tsv.extract.sh
bash continuous-4559-both_sexes.tsv.extract.sh
bash continuous-46-both_sexes-irnt.tsv.extract.sh
bash continuous-5085-both_sexes-irnt.tsv.extract.sh
bash continuous-50-both_sexes-irnt.tsv.extract.sh
bash continuous-5104-both_sexes-irnt.tsv.extract.sh
bash continuous-5105-both_sexes-irnt.tsv.extract.sh
bash continuous-5110-both_sexes-irnt.tsv.extract.sh
bash continuous-5116-both_sexes-irnt.tsv.extract.sh
bash continuous-5134-both_sexes-irnt.tsv.extract.sh
bash continuous-5157-both_sexes-irnt.tsv.extract.sh
bash continuous-5257-both_sexes-irnt.tsv.extract.sh
bash continuous-5263-both_sexes-irnt.tsv.extract.sh
bash continuous-5984-both_sexes-irnt.tsv.extract.sh
bash continuous-6033-both_sexes-irnt.tsv.extract.sh
bash continuous-728-both_sexes.tsv.extract.sh
bash continuous-845-both_sexes.tsv.extract.sh
bash continuous-874-both_sexes-irnt.tsv.extract.sh
bash continuous-924-both_sexes.tsv.extract.sh
bash continuous-94-both_sexes-irnt.tsv.extract.sh
bash icd10-C44-both_sexes.tsv.extract.sh
bash icd10-C50-both_sexes.tsv.extract.sh
bash icd10-D12-both_sexes.tsv.extract.sh
bash icd10-E03-both_sexes.tsv.extract.sh
bash icd10-E11-both_sexes.tsv.extract.sh
bash icd10-E66-both_sexes.tsv.extract.sh
bash icd10-F32-both_sexes.tsv.extract.sh
bash icd10-G47-both_sexes.tsv.extract.sh
bash icd10-G56-both_sexes.tsv.extract.sh
bash icd10-H33-both_sexes.tsv.extract.sh
bash icd10-I25-both_sexes.tsv.extract.sh
bash icd10-I48-both_sexes.tsv.extract.sh
bash icd10-I83-both_sexes.tsv.extract.sh
bash icd10-I84-both_sexes.tsv.extract.sh
bash icd10-J33-both_sexes.tsv.extract.sh
bash icd10-J44-both_sexes.tsv.extract.sh
bash icd10-K40-both_sexes.tsv.extract.sh
bash icd10-K42-both_sexes.tsv.extract.sh
bash icd10-K44-both_sexes.tsv.extract.sh
bash icd10-K52-both_sexes.tsv.extract.sh
bash icd10-K57-both_sexes.tsv.extract.sh
bash icd10-K80-both_sexes.tsv.extract.sh
bash icd10-M16-both_sexes.tsv.extract.sh
bash icd10-M17-both_sexes.tsv.extract.sh
bash icd10-M20-both_sexes.tsv.extract.sh
bash icd10-M51-both_sexes.tsv.extract.sh
bash icd10-M72-both_sexes.tsv.extract.sh
bash icd10-M75-both_sexes.tsv.extract.sh
bash icd10-N20-both_sexes.tsv.extract.sh
bash icd10-N81-both_sexes.tsv.extract.sh
